"""Jest模板生成器 - 配置文件、测试头部、占位测试。
STATUS: UNVERIFIED - 未经实战验证，参考pytest_gen/mdi.parser使用
"""

from __future__ import annotations


def generate_jest_config() -> str:
    return (
        "/**\n"
        " * Jest configuration for MDI-generated API tests.\n"
        " */\n"
        "module.exports = {\n"
        "  testEnvironment: 'node',\n"
        "  testMatch: ['**/*.test.js'],\n"
        "  testTimeout: 10000,\n"
        "};\n"
    )


def generate_test_header(title: str, base_url: str) -> list[str]:
    lines: list[str] = []
    lines.append("/**")
    lines.append(f" * Jest tests for {title}.")
    lines.append(" * Auto-generated by MDI.")
    lines.append(" */")
    lines.append("")
    lines.append("const axios = require('axios');")
    lines.append("")
    lines.append(f"const BASE_URL = process.env.API_BASE_URL || '{base_url}';")
    lines.append("const API_TOKEN = process.env.API_TOKEN || null;")
    lines.append("")
    lines.append("const apiClient = axios.create({")
    lines.append("  baseURL: BASE_URL,")
    lines.append("  headers: {")
    lines.append("    'Content-Type': 'application/json',")
    lines.append("    ...(API_TOKEN && { 'Authorization': `Bearer ${API_TOKEN}` }),")
    lines.append("  },")
    lines.append("});")
    lines.append("")
    return lines


def generate_placeholder_tests() -> list[str]:
    lines: list[str] = []
    lines.append("// TODO: 未发现接口定义，请检查MDI文档")
    lines.append("test('placeholder', () => {")
    lines.append("  expect(true).toBe(true);")
    lines.append("});")
    lines.append("")
    return lines
