#!/bin/bash
# =============================================================================
# conda-perf-setup.sh — Conda/mamba 性能优化配置脚本（共享可复用 v1.0）
#
# 用途：在 Docker 构建/CI 环境中一键配置高性能 conda 环境，包括：
#   1. 写入性能优化版 .condarc（并行线程、超时重试、镜像源）
#   2. 设置 libmamba 为默认 solver
#   3. 验证 mamba/conda 可用性和版本
#
# 用法（作为独立脚本执行，写入 .condarc + 配置 solver）：
#   CONDA_MIRROR=tuna CONDA_THREADS=8 /path/to/conda-perf-setup.sh
#
# 用法（source 到当前 shell，获取辅助函数）：
#   source /path/to/conda-perf-setup.sh
#   mamba_create_env myenv python=3.14 numpy pandas
#
# 环境变量：
#   CONDA_DIR       conda 安装根目录（默认 /opt/conda）
#   CONDA_MIRROR    镜像源: official | tuna | aliyun（默认 official）
#   CONDA_THREADS   并行下载/解压线程数（默认 8）
#   CONDA_TIMEOUT   读取超时秒数（默认 120）
#   CONDA_RETRIES   最大重试次数（默认 5）
#   CONDA_OUTPUT    .condarc 写入路径（默认 /root/.condarc）
#
# 提供的函数（仅 source 时可用）：
#   mamba_create_env <env_name> [packages...]
#       使用 mamba 一次性创建环境（单次 solver），含计时和错误处理
#   conda_perf_verify
#       验证 conda/mamba 配置正确性
#
# 引用规范：
#   其他项目使用时，COPY 本脚本到 /usr/local/bin/ 或 /tmp/ 后执行即可。
#   配合 BuildKit cache mount (--mount=type=cache,target=/opt/conda/pkgs) 效果最佳。
# =============================================================================

# 注意：本脚本面向 Miniforge3 + mamba 栈，不覆盖 Micromamba（使用 .mambarc 配置）。
#       Miniconda3 用户需先 `conda install -n base -c conda-forge mamba` 安装 mamba CLI。
#       最简用法（静态配置）：直接 COPY condarc-performant.yaml 为 /root/.condarc
#       高级用法（动态镜像/线程）：运行本脚本或 source 获取 mamba_create_env 函数
set -euo pipefail

# ── 默认参数 ──
CONDA_DIR="${CONDA_DIR:-/opt/conda}"
CONDA_MIRROR="${CONDA_MIRROR:-official}"
CONDA_THREADS="${CONDA_THREADS:-8}"
CONDA_RETRIES="${CONDA_RETRIES:-5}"
CONDA_OUTPUT="${CONDA_OUTPUT:-/root/.condarc}"

# 根据镜像源自动调整超时（官方源较慢，国内镜像较快）
# 若用户显式设置了 CONDA_TIMEOUT 则使用用户值
if [ -z "${CONDA_TIMEOUT+x}" ]; then
    case "${CONDA_MIRROR}" in
        official) CONDA_TIMEOUT=300 ;;
        *)        CONDA_TIMEOUT=120 ;;
    esac
fi

# ── 日志函数（独立脚本时用简单输出，source 时不覆盖已有日志函数） ──
if ! declare -f log_info &>/dev/null; then
    _cps_color() { [ -t 1 ] && printf '\033[%sm' "$1" || true; }
    _cps_reset() { [ -t 1 ] && printf '\033[0m' || true; }
    _cps_info()  { echo "$(_cps_color 32)[INFO]$(_cps_reset) $*"; }
    _cps_ok()    { echo "$(_cps_color 32)[OK]$(_cps_reset) $*"; }
    _cps_warn()  { echo "$(_cps_color 33)[WARN]$(_cps_reset) $*" >&2; }
    _cps_error() { echo "$(_cps_color 31)[ERROR]$(_cps_reset) $*" >&2; }
    _cps_step()  { echo ""; echo "$(_cps_color 1;34)━━━ $* ━━━$(_cps_reset)"; echo ""; }
else
    _cps_info()  { log_info "$@"; }
    _cps_ok()    { log_ok "$@"; }
    _cps_warn()  { log_warn "$@"; }
    _cps_error() { log_error "$@"; }
    _cps_step()  { log_step "$@"; }
fi

# ── 核心函数：生成并写入 .condarc ──
_cps_write_condarc() {
    local mirror="$1" threads="$2" timeout="$3" retries="$4" output="$5"

    _cps_info "Generating .condarc (mirror=${mirror}, threads=${threads}, timeout=${timeout}s, retries=${retries})"

    # 根据镜像源选择 channels
    local channels_line
    case "${mirror}" in
        tuna)
            channels_line="  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/"
            _cps_info "Using Tsinghua TUNA conda-forge mirror"
            ;;
        aliyun)
            channels_line="  - https://mirrors.aliyun.com/anaconda/cloud/conda-forge/"
            _cps_info "Using Aliyun conda-forge mirror"
            ;;
        official|*)
            channels_line="  - conda-forge"
            _cps_info "Using official conda-forge channels"
            ;;
    esac

    # 确保输出目录存在
    mkdir -p "$(dirname "${output}")"

    # 写入 .condarc
    cat > "${output}" <<EOF
# ── Conda Performance Config (generated by conda-perf-setup.sh v1.0) ──
# Mirror: ${mirror} | Threads: ${threads} | Timeout: ${timeout}s | Retries: ${retries}
channels:
${channels_line}
channel_priority: strict
show_channel_urls: false
remote_connect_timeout_secs: 30
remote_read_timeout_secs: ${timeout}
remote_max_retries: ${retries}
remote_backoff_factor: 3
repodata_threads: ${threads}
execute_threads: ${threads}
ssl_verify: true
EOF

    _cps_ok ".condarc written to ${output}"
}

# ── 核心函数：设置 libmamba solver ──
_cps_set_solver() {
    local conda_bin="$1"
    _cps_info "Setting libmamba as default solver..."
    "${conda_bin}" config --set solver libmamba 2>/dev/null || {
        _cps_warn "Could not set solver via conda config (libmamba may not be installed yet)"
        return 0
    }
    local current_solver
    current_solver=$("${conda_bin}" config --show solver 2>/dev/null | tr -d ' ' | cut -d: -f2 || echo "unknown")
    _cps_ok "Default solver: ${current_solver}"
}

# ── 核心函数：验证 conda/mamba 可用性 ──
_cps_verify() {
    local conda_dir="$1"
    local conda_bin="${conda_dir}/bin/conda"
    local mamba_bin="${conda_dir}/bin/mamba"

    if [ -x "${conda_bin}" ]; then
        _cps_ok "conda: $("${conda_bin}" --version 2>&1)"
    else
        _cps_warn "conda not found at ${conda_bin}"
    fi

    if [ -x "${mamba_bin}" ]; then
        _cps_ok "mamba: $("${mamba_bin}" --version 2>&1 | head -1)"
    else
        _cps_warn "mamba not found at ${mamba_bin} (libmamba solver will be used via conda --solver=libmamba)"
    fi
}

# ── source 专用函数：mamba_create_env ──
# 用法：mamba_create_env <env_name> [packages...]
# 优势：单次 mamba create（一次 solver）+ 内联计时 + 错误处理 + 自动 conda-forge channel
mamba_create_env() {
    local env_name="$1"
    shift
    local packages=("$@")

    if [ -z "${env_name}" ]; then
        _cps_error "mamba_create_env: environment name required"
        return 1
    fi

    if [ ${#packages[@]} -eq 0 ]; then
        _cps_error "mamba_create_env: at least one package required"
        return 1
    fi

    local mamba_bin="${CONDA_DIR}/bin/mamba"
    local conda_bin="${CONDA_DIR}/bin/conda"
    local cli_bin cli_name
    if [ -x "${mamba_bin}" ]; then
        cli_bin="${mamba_bin}"
        cli_name="mamba"
    elif command -v mamba &>/dev/null; then
        cli_bin="mamba"
        cli_name="mamba"
    elif [ -x "${conda_bin}" ]; then
        cli_bin="${conda_bin}"
        cli_name="conda (with --solver=libmamba)"
        _cps_warn "mamba not found, falling back to conda --solver=libmamba (slower than native mamba)"
    else
        _cps_error "Neither mamba nor conda found in CONDA_DIR=${CONDA_DIR} or PATH"
        return 1
    fi

    _cps_step "Creating conda env '${env_name}' with ${cli_name} (single solve, ${CONDA_THREADS} threads)"
    _cps_info "Packages: ${packages[*]}"

    local start_time elapsed rc
    start_time=$(date +%s)
    set +e
    if [ "${cli_name}" = "mamba" ]; then
        "${cli_bin}" create -y -n "${env_name}" -c conda-forge --override-channels -q "${packages[@]}" 2>&1
    else
        "${cli_bin}" create -y -n "${env_name}" -c conda-forge --override-channels -q --solver=libmamba "${packages[@]}" 2>&1
    fi
    rc=$?
    set -e
    elapsed=$(($(date +%s) - start_time))

    if [ $rc -eq 0 ]; then
        _cps_ok "Environment '${env_name}' created in ${elapsed}s"
        return 0
    else
        _cps_error "Failed to create environment '${env_name}' after ${elapsed}s (exit code: $rc)"
        return $rc
    fi
}

# ── source 专用函数：conda_perf_verify ──
conda_perf_verify() {
    _cps_step "Conda Performance Configuration Verification"
    _cps_verify "${CONDA_DIR}"

    # 检查 .condarc 关键参数
    if [ -f "${CONDA_OUTPUT}" ]; then
        _cps_ok ".condarc exists at ${CONDA_OUTPUT}"
        local threads
        threads=$(grep -E '^(repodata|execute)_threads' "${CONDA_OUTPUT}" | head -1 | awk '{print $2}')
        _cps_info "Configured threads: ${threads:-unknown}"
    else
        _cps_warn ".condarc not found at ${CONDA_OUTPUT}"
    fi
}

# ── 主流程（仅在直接执行时运行，source 时不执行） ──
_cps_is_sourced() {
    # 检测是否被 source（Bash/Zsh 兼容）
    if [ -n "${BASH_SOURCE:-}" ]; then
        [ "${BASH_SOURCE[0]}" != "$0" ]
    elif [ -n "${ZSH_VERSION:-}" ]; then
        [ "${ZSH_EVAL_CONTEXT:-}" = "toplevel:file" ]
    else
        return 1
    fi
}

if ! _cps_is_sourced; then
    _cps_step "Conda Performance Setup v1.0"
    _cps_info "CONDA_DIR=${CONDA_DIR}"
    _cps_info "CONDA_MIRROR=${CONDA_MIRROR}"
    _cps_info "CONDA_THREADS=${CONDA_THREADS}"

    # Step 1: 写入 .condarc
    _cps_write_condarc "${CONDA_MIRROR}" "${CONDA_THREADS}" "${CONDA_TIMEOUT}" "${CONDA_RETRIES}" "${CONDA_OUTPUT}"

    # Step 2: 设置 solver（conda 可用时）
    if [ -x "${CONDA_DIR}/bin/conda" ]; then
        _cps_set_solver "${CONDA_DIR}/bin/conda"
    elif command -v conda &>/dev/null; then
        _cps_set_solver "$(command -v conda)"
    else
        _cps_warn "conda not found, skipping solver setup (run this script after conda installation)"
    fi

    # Step 3: 验证
    _cps_verify "${CONDA_DIR}"

    _cps_step "Setup Complete"
    _cps_ok "Conda performance configuration applied successfully"
fi
