"""数据模型导出。分层约束：``models`` 只依赖 ``crypto`` 常量，不得反向依赖
``services`` / ``api``。
"""

from .catalog import (
    Capability,
    Catalog,
    ModelEntry,
    Provider,
    ProviderProtocol,
    Tier,
)
from .identity import (
    RECOVERY_PREFIX,
    TOKEN_PREFIX,
    RecoveryRecord,
    Role,
    TokenRecord,
    TokenStatus,
    User,
)
from .ops import (
    ORDER_TRANSITIONS,
    AdItem,
    AdminConfig,
    AuditEvent,
    NewsItem,
    OrderStatus,
    PaymentOrder,
)
from .routing import (
    ALIAS_CAPABILITIES,
    COMBO_SEPARATOR,
    COMPRESSION_SPECS,
    DEFAULT_ALIAS,
    STRATEGIES,
    STRATEGY_LABELS,
    AttemptRecord,
    CompressionLevel,
    RouteDecision,
    RouteRequest,
    UserSettings,
    parse_combo,
    resolve_capability,
)
from .usage import (
    BillingEvent,
    BillingEventKind,
    CallStatus,
    UsageRecord,
    UsageSummary,
)
from .vault import (
    CipherBlob,
    EscrowBlob,
    EscrowRecord,
    KeyStatus,
    VaultKeyRecord,
)

__all__ = [
    "ALIAS_CAPABILITIES",
    "COMBO_SEPARATOR",
    "COMPRESSION_SPECS",
    "DEFAULT_ALIAS",
    "ORDER_TRANSITIONS",
    "RECOVERY_PREFIX",
    "STRATEGIES",
    "STRATEGY_LABELS",
    "TOKEN_PREFIX",
    "AdItem",
    "AdminConfig",
    "AttemptRecord",
    "AuditEvent",
    "BillingEvent",
    "BillingEventKind",
    "CallStatus",
    "Capability",
    "Catalog",
    "CipherBlob",
    "CompressionLevel",
    "EscrowBlob",
    "EscrowRecord",
    "KeyStatus",
    "ModelEntry",
    "NewsItem",
    "OrderStatus",
    "ORDER_TRANSITIONS",
    "PaymentOrder",
    "Provider",
    "ProviderProtocol",
    "RecoveryRecord",
    "Role",
    "RouteDecision",
    "RouteRequest",
    "Tier",
    "TokenRecord",
    "TokenStatus",
    "UsageRecord",
    "UsageSummary",
    "User",
    "UserSettings",
    "VaultKeyRecord",
    "parse_combo",
    "resolve_capability",
]
