id = "docs-knowledge-learning-04-docs-markup-tooling-executablebooks-myst-guide-examples-poc-index"
title = "概念验证"
category = "knowledge/learning/04-docs-markup-tooling/executablebooks-myst-guide/examples/poc"
date = "2026-07-02"
version = "1.0"
