"""提示词萃取系统 —— 常量包统一导出

将所有分散在各业务模块中的硬编码常量集中至此包，
提供统一导入入口，消除跨模块重复定义。
"""

from prompt_extraction.constants.thresholds import (
    # 质量评估阈值
    QUALITY_THRESHOLD,
    CLARITY_WEIGHT,
    COMPLETENESS_WEIGHT,
    EXECUTABILITY_WEIGHT,
    GRADE_THRESHOLDS,
    # 文本长度评估
    TEXT_TOO_SHORT_LENGTH,
    TEXT_TOO_LONG_LENGTH,
    SCORE_DEDUCTION_TOO_SHORT,
    SCORE_DEDUCTION_TOO_LONG,
    # 结构层次评估
    SCORE_DEDUCTION_PER_MISSING_STRUCTURE,
    # 歧义度评估
    SCORE_DEDUCTION_PER_AMBIGUOUS,
    SCORE_DEDUCTION_AMBIGUOUS_MAX,
    # 完整性分值
    SCORE_INSTRUCTION,
    SCORE_CONSTRAINT,
    SCORE_CONTEXT,
    SCORE_EXAMPLE,
    SCORE_OUTPUT_FORMAT,
    # 上下文检测
    CONTEXT_LENGTH_THRESHOLD,
    # 可执行性评估
    VERB_SCORE_PER,
    VERB_SCORE_MAX,
    CONSTRAINT_VERIFIABLE_SCORE_MAX,
    OUTPUT_DETERMINABLE_SCORE,
    OUTPUT_TYPE_PARTIAL_SCORE,
    # 通用常量
    ID_HEX_LENGTH,
    TEXT_TRUNCATE_LENGTH,
    DESC_TRUNCATE_LENGTH,
)

from prompt_extraction.constants.keywords import (
    # 质量评估 —— 词汇表
    AMBIGUOUS_WORDS,
    ACTION_VERBS,
    BACKGROUND_KEYWORDS,
    EXAMPLE_KEYWORDS,
    VERIFIABLE_CONSTRAINT_KEYWORDS,
    # 特征提取 —— 词汇表
    INSTRUCTION_KEYWORDS,
    IMPERATIVE_PREFIXES,
    CONSTRAINT_TYPE_MAP,
    OUTPUT_KEYWORDS,
    OUTPUT_TYPE_MAP,
    # 优化器 —— 词汇表
    AMBIGUITY_MAP,
    CONTEXT_EXTRACT_KEYWORDS,
    # 标准化器 —— 词汇表
    PUNCTUATION_MAP,
    # 解析器 —— 词汇表
    PROMPT_COLUMN_KEYWORDS,
    FORMAT_MAP,
    # UI 共用常量
    GRADE_ORDER,
    GRADE_COLORS,
    GRADE_DEFAULT_COLOR,
    RADAR_CATEGORIES,
)

from prompt_extraction.constants.paths import (
    DEFAULT_OUTPUT_DIR,
)

from prompt_extraction.constants import patterns as _patterns
from prompt_extraction.constants import styles as _styles

# 导出 patterns 模块中预编译的正则对象
from prompt_extraction.constants.patterns import (
    RE_HEADING,
    RE_PARAGRAPH_SPLIT,
    RE_LIST_MARKER,
    RE_DIGIT,
    RE_SENTENCE_SPLIT,
    RE_MARKDOWN_BLOCK,
    RE_WHITESPACE,
    RE_HTML_TAG,
    RE_IMAGE,
    RE_LINK,
    RE_BOLD_ASTERISK,
    RE_BOLD_UNDERSCORE,
    RE_ITALIC_ASTERISK,
    RE_ITALIC_UNDERSCORE,
    RE_STRIKETHROUGH,
    RE_CODE_BLOCK,
    RE_INLINE_CODE,
    RE_HEADING_MARKER,
    RE_BLOCKQUOTE,
    RE_UNORDERED_LIST,
    RE_ORDERED_LIST,
    RE_HR,
    RE_MD_HEADING_EXTRACT,
    RE_MD_UNORDERED_ITEM,
    RE_MD_ORDERED_ITEM,
    RE_MD_CODE_BLOCK_EXTRACT,
    RE_URL,
    RE_EMAIL,
)

# 导出 styles 模块中的样式常量
from prompt_extraction.constants.styles import (
    GRADE_LABEL_STYLE,
    GRADE_VALUE_STYLE,
    GRADE_CONTAINER_STYLE,
    RADAR_LINE_COLOR,
    RADAR_LINE_WIDTH,
    RADAR_FILL_COLOR,
    RADAR_GRID_COLOR,
    RADAR_TICK_FONT_SIZE,
    RADAR_ANGULAR_TICK_FONT_SIZE,
    RADAR_RANGE_MIN,
    RADAR_RANGE_MAX,
    RADAR_HEIGHT,
    RADAR_MARGIN,
)

__all__ = [
    # thresholds
    "QUALITY_THRESHOLD",
    "CLARITY_WEIGHT",
    "COMPLETENESS_WEIGHT",
    "EXECUTABILITY_WEIGHT",
    "GRADE_THRESHOLDS",
    "TEXT_TOO_SHORT_LENGTH",
    "TEXT_TOO_LONG_LENGTH",
    "SCORE_DEDUCTION_TOO_SHORT",
    "SCORE_DEDUCTION_TOO_LONG",
    "SCORE_DEDUCTION_PER_MISSING_STRUCTURE",
    "SCORE_DEDUCTION_PER_AMBIGUOUS",
    "SCORE_DEDUCTION_AMBIGUOUS_MAX",
    "SCORE_INSTRUCTION",
    "SCORE_CONSTRAINT",
    "SCORE_CONTEXT",
    "SCORE_EXAMPLE",
    "SCORE_OUTPUT_FORMAT",
    "CONTEXT_LENGTH_THRESHOLD",
    "VERB_SCORE_PER",
    "VERB_SCORE_MAX",
    "CONSTRAINT_VERIFIABLE_SCORE_MAX",
    "OUTPUT_DETERMINABLE_SCORE",
    "OUTPUT_TYPE_PARTIAL_SCORE",
    "ID_HEX_LENGTH",
    "TEXT_TRUNCATE_LENGTH",
    "DESC_TRUNCATE_LENGTH",
    # keywords
    "AMBIGUOUS_WORDS",
    "ACTION_VERBS",
    "BACKGROUND_KEYWORDS",
    "EXAMPLE_KEYWORDS",
    "VERIFIABLE_CONSTRAINT_KEYWORDS",
    "INSTRUCTION_KEYWORDS",
    "IMPERATIVE_PREFIXES",
    "CONSTRAINT_TYPE_MAP",
    "OUTPUT_KEYWORDS",
    "OUTPUT_TYPE_MAP",
    "AMBIGUITY_MAP",
    "CONTEXT_EXTRACT_KEYWORDS",
    "PUNCTUATION_MAP",
    "PROMPT_COLUMN_KEYWORDS",
    "FORMAT_MAP",
    "GRADE_ORDER",
    "GRADE_COLORS",
    "GRADE_DEFAULT_COLOR",
    "RADAR_CATEGORIES",
    # paths
    "DEFAULT_OUTPUT_DIR",
    # patterns
    "RE_HEADING",
    "RE_PARAGRAPH_SPLIT",
    "RE_LIST_MARKER",
    "RE_DIGIT",
    "RE_SENTENCE_SPLIT",
    "RE_MARKDOWN_BLOCK",
    "RE_WHITESPACE",
    "RE_HTML_TAG",
    "RE_IMAGE",
    "RE_LINK",
    "RE_BOLD_ASTERISK",
    "RE_BOLD_UNDERSCORE",
    "RE_ITALIC_ASTERISK",
    "RE_ITALIC_UNDERSCORE",
    "RE_STRIKETHROUGH",
    "RE_CODE_BLOCK",
    "RE_INLINE_CODE",
    "RE_HEADING_MARKER",
    "RE_BLOCKQUOTE",
    "RE_UNORDERED_LIST",
    "RE_ORDERED_LIST",
    "RE_HR",
    "RE_MD_HEADING_EXTRACT",
    "RE_MD_UNORDERED_ITEM",
    "RE_MD_ORDERED_ITEM",
    "RE_MD_CODE_BLOCK_EXTRACT",
    "RE_URL",
    "RE_EMAIL",
    # styles
    "GRADE_LABEL_STYLE",
    "GRADE_VALUE_STYLE",
    "GRADE_CONTAINER_STYLE",
    "RADAR_LINE_COLOR",
    "RADAR_LINE_WIDTH",
    "RADAR_FILL_COLOR",
    "RADAR_GRID_COLOR",
    "RADAR_TICK_FONT_SIZE",
    "RADAR_ANGULAR_TICK_FONT_SIZE",
    "RADAR_RANGE_MIN",
    "RADAR_RANGE_MAX",
    "RADAR_HEIGHT",
    "RADAR_MARGIN",
]
