id = "docs-knowledge-learning-04-docs-markup-tooling-executablebooks-myst-guide-resources-index"
title = "补充资源"
category = "knowledge/learning/04-docs-markup-tooling/executablebooks-myst-guide/resources"
date = "2026-07-15"
version = "1.0"
