#!/usr/bin/env python3
"""目录 README 自动生成与索引更新工具。

批量为缺失 README.md 的内容聚合目录生成标准化入口文档，支持两种策略：
  - Strategy B（模板生成）：扫描当前目录下的 .md 文件，提取 frontmatter 元数据，
    生成索引表 + 子目录导航
  - Strategy C（自动索引）：递归扫描子目录，生成层级索引结构
  - 增量更新（--update）：重新扫描目录，更新已有 README 中标记区域内的索引表，
    保留用户自定义的概述、相关资源等手动编辑内容；自动升级旧版无标记 README

用法：
  python generate-readme.py --scan                     # 仅扫描缺失 README 的目录
  python generate-readme.py --target-dir <dir>         # 为指定目录生成 README
  python generate-readme.py --p1                       # 批量处理 P1 阶段内容聚合目录
  python generate-readme.py --all                      # 处理所有缺失 README 的目录
  python generate-readme.py --update                   # 增量更新所有脚本生成的 README 索引
  python generate-readme.py --update --target-dir <dir> # 更新指定目录的 README 索引
  python generate-readme.py --update --dry-run         # 预览索引更新
  python generate-readme.py --target-dir <dir> --force # 覆盖已存在的 README
"""

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from constants import EXCLUDED_DIRS
from lib.frontmatter import parse_frontmatter_unified
from lib.markdown import extract_title, extract_description, update_marker_region
from lib.project import resolve_project_root
from lib.cli import setup_safe_output, print_pass, print_warn, print_error, print_header


TITLE_FROM_DIRNAME_RE = re.compile(r'[_\-]+')

README_INDEX_START = "<!-- README_INDEX_START -->"
README_INDEX_END = "<!-- README_INDEX_END -->"
GENERATED_FOOTER_PREFIX = "<!-- generated by generate-readme.py"

DIR_TITLE_MAP: dict[str, str] = {
    "04-docs-markup-tooling": "文档标记与工具链",
    "05-ai-multimodal-content": "AI多模态内容",
    "06-business-trends-analysis": "商业趋势分析",
    "07-vendor-product-learning": "厂商产品学习",
    "08-systems-infrastructure": "系统基础设施",
    "okr-wiki": "OKR 方法论知识库",
    "agent-communication-protocols": "Agent 通信协议",
    "agent-interface-deep-dive": "Agent 接口深度解析",
    "agent-skills-wiki": "Agent 技能知识库",
    "ffi-wiki": "FFI 跨语言调用",
    "idl-wiki": "IDL 接口定义语言",
    "interface-api-abi-protocol-wiki": "Interface/API/ABI/Protocol 四层技术栈",
    "harness-engineering-wiki": "Harness 工程化",
    "headroom-context-compression-wiki": "上下文窗口与压缩技术",
    "karpathy-llm-coding-guidelines": "Karpathy LLM 编码指南",
    "longcat-agent-learning-wiki": "LongCat Agent 学习",
    "claude-tag-article": "Claude 标签文章分析",
    "minitest-mobile-use-wiki": "Minitest 移动端自动化测试",
    "mopmonk-security-agent-wiki": "MopMonk 安全 Agent",
    "open-code-review-wiki": "开放式代码审查",
    "rainman-translate-book-wiki": "Rainman 翻译书籍",
    "scikit-build-core-wiki": "scikit-build-core 构建系统",
    "ai-monetization-wiki": "AI 商业化",
    "papi-jiang-solo-ip-trend-wiki": "Papi酱单人IP趋势分析",
    "sunlogin": "向日葵远程控制",
    "tuya": "涂鸦智能",
    "volcengine": "火山引擎",
    "appendix": "附录",
    "concepts": "核心概念",
    "implementation": "实施指南",
    "methods": "方法论",
    "scoring": "评分体系",
    "templates": "模板库",
    "tools": "工具集",
    "assets": "资产目录",
    "plans": "方案文档",
    "specs": "规格文档",
    "creative-design": "创意设计模式",
    "document-architecture": "文档架构模式",
    "governance-strategy": "治理策略模式",
    "product-growth": "产品增长模式",
    "retrospective-knowledge": "复盘知识沉淀模式",
    "tools-automation": "工具自动化模式",
    "ai-collaboration": "AI 协作模式",
    "retrospective-myst-unified-ecosystem-phase1-20260705": "MyST 统一生态系统一期复盘",
    "myst-to-agentspec-migration-analysis": "MyST 到 AgentSpec 迁移分析",
    "01-getting-started": "入门指南",
    "02-suite-management": "测试套件管理",
    "03-running-tests": "运行测试",
    "04-triage-and-integrations": "问题排查与集成",
    "05-reference": "参考手册",
    "01-introduction-installation": "介绍与安装",
    "02-quickstarts": "快速开始",
    "03-core-concepts": "核心概念",
    "04-examples": "示例",
    "05-sdk-reference": "SDK 参考",
    "06-troubleshooting": "故障排查",
    "minitest-docs": "Minitest 文档",
    "mobile-use-sdk-docs": "Mobile Use SDK 文档",
    "executablebooks-myst-guide": "ExecutableBooks MyST 指南",
    "myst-markdown-tutorial": "MyST Markdown 教程",
    "examples": "示例",
    "poc": "概念验证",
    "sunlogin-bootbox-analysis": "向日葵 Bootbox 分析",
    "sunlogin-offline-hardware-wiki": "向日葵离线硬件知识库",
    "atoms": "原子化拆分",
    "exports": "导出产物",
    "insights": "洞察萃取",
    "laws": "规律总结",
    "patterns": "模式沉淀",
    "insight-extraction": "洞察萃取",
    "external-learning": "外部学习",
    "iot-ecosystem": "IoT 生态系统",
    "meta-methodology": "元方法论",
    "toolchain-dev": "工具链开发",
    "execution": "执行记录",
    "export": "导出报告",
    "actions": "行动方案",
    "action-plan": "行动计划",
    "decisions": "决策记录",
    "issues": "问题清单",
    "knowledge": "知识沉淀",
    "phases": "阶段规划",
    "risks": "风险分析",
    "suggestions": "改进建议",
    "task-reports": "任务复盘报告",
    "project-reports": "项目报告",
    "competitive-analysis": "竞品分析",
    "standards-tools": "标准与工具",
    "project-governance": "项目治理",
    "comprehensive-reviews": "综合评审",
    "retrospective-specweave-full-project-comprehensive-20260626": "SpecWeave 全项目综合复盘",
    "retrospective-ffi-wiki-tutorial-20260705": "FFI Wiki 教程复盘",
    "retrospective-myst-unified-ecosystem-phase1-20260704": "MyST 统一生态系统一期复盘（早期）",
    "retrospective-tvm-ffi-wiki-tutorial-20260705": "TVM FFI Wiki 教程复盘",
    "retrospective-architecture-priority-20260629": "架构优先级复盘",
    "retrospective-firecrawl-learning-20260629": "Firecrawl 学习复盘",
    "retrospective-home-assistant-integration-20260630": "Home Assistant 集成复盘",
    "retrospective-home-assistant-tuya-official-20260630": "Home Assistant+涂鸦官方复盘",
    "retrospective-tuya-projects-for-xlsx-agentization-20260701": "涂鸦项目XLSX Agent化复盘",
    "retrospective-tuyaopen-analysis-20260630": "TuyaOpen 分析复盘",
    "retrospective-trae-contest-faq-analysis-20260624": "Trae 竞赛FAQ分析复盘",
    "retrospective-tuyaopen-dev-skills-learning-20260630": "TuyaOpen 开发技能学习复盘",
    "retrospective-tuyaopen-learning-report-optimization-20260630": "TuyaOpen 学习报告优化复盘",
}


def humanize_dirname(dirname: str) -> str:
    if dirname in DIR_TITLE_MAP:
        return DIR_TITLE_MAP[dirname]
    parts = TITLE_FROM_DIRNAME_RE.split(dirname)
    result = []
    for p in parts:
        if not p:
            continue
        if p.isascii() and p.isalpha() and len(p) > 1:
            result.append(p.capitalize())
        else:
            result.append(p)
    return ' '.join(result) if result else dirname


@dataclass
class DocEntry:
    filename: str
    title: str
    summary: str
    tags: list[str] = field(default_factory=list)
    maturity: str = ""


@dataclass
class DirEntry:
    dirname: str
    readme_exists: bool
    md_count: int
    subdir_count: int


def infer_category(dir_path: Path, root: Path) -> str:
    try:
        rel = dir_path.relative_to(root / 'docs')
        parts = rel.parts
        if parts:
            return parts[0]
    except ValueError:
        pass
    return "docs"


def infer_id(dir_path: Path, root: Path) -> str:
    try:
        rel = dir_path.relative_to(root)
        return str(rel).replace('\\', '-').replace('/', '-') + '-index'
    except ValueError:
        return dir_path.name + '-index'


def scan_directory(dir_path: Path, root: Path) -> tuple[list[DocEntry], list[DirEntry]]:
    doc_entries = []
    dir_entries = []

    for item in sorted(dir_path.iterdir()):
        if item.name.startswith('.'):
            continue
        if item.name == 'README.md':
            continue

        if item.is_file() and item.suffix.lower() == '.md':
            meta = parse_frontmatter_unified(item)
            title = ""
            summary = ""
            tags = []
            maturity = ""

            if meta:
                title = str(meta.get('title', ''))
                summary = str(meta.get('summary', ''))
                tags_val = meta.get('tags', [])
                if isinstance(tags_val, list):
                    tags = [str(t) for t in tags_val]
                maturity = str(meta.get('maturity', ''))

            if not title:
                title = extract_title(item)
            if not title:
                title = humanize_dirname(item.stem)

            if not summary:
                summary = extract_description(item)
            if not summary:
                summary = title

            doc_entries.append(DocEntry(
                filename=item.name,
                title=title,
                summary=summary,
                tags=tags,
                maturity=maturity,
            ))

        elif item.is_dir():
            parts = set(item.parts)
            if EXCLUDED_DIRS & parts:
                continue
            sub_readme = item / 'README.md'
            sub_md_count = len(list(item.glob('*.md')))
            sub_subdirs = len([d for d in item.iterdir() if d.is_dir() and not d.name.startswith('.')])
            dir_entries.append(DirEntry(
                dirname=item.name,
                readme_exists=sub_readme.exists(),
                md_count=sub_md_count,
                subdir_count=sub_subdirs,
            ))

    return doc_entries, dir_entries


def generate_index_tables(
    doc_entries: list[DocEntry],
    dir_entries: list[DirEntry],
) -> str:
    lines = []

    if doc_entries:
        lines.append("## 📄 文档索引")
        lines.append("")
        has_maturity = any(e.maturity for e in doc_entries)
        if has_maturity:
            lines.append("| 文档 | 说明 | 成熟度 | 标签 |")
            lines.append("|------|------|--------|------|")
            for e in doc_entries:
                tags_str = ' '.join(f'`{t}`' for t in e.tags[:3]) if e.tags else ""
                mat = e.maturity if e.maturity else "-"
                lines.append(f"| [{e.title}]({e.filename}) | {e.summary} | {mat} | {tags_str} |")
        else:
            lines.append("| 文档 | 说明 | 标签 |")
            lines.append("|------|------|------|")
            for e in doc_entries:
                tags_str = ' '.join(f'`{t}`' for t in e.tags[:3]) if e.tags else ""
                lines.append(f"| [{e.title}]({e.filename}) | {e.summary} | {tags_str} |")
        lines.append("")

    if dir_entries:
        lines.append("## 📁 子目录导航")
        lines.append("")
        lines.append("| 子目录 | 文档数 | 说明 |")
        lines.append("|--------|--------|------|")
        for d in dir_entries:
            status = "✅" if d.readme_exists else "📋"
            label = humanize_dirname(d.dirname)
            link = f"{d.dirname}/README.md" if d.readme_exists else f"{d.dirname}/"
            extra = f"（{d.subdir_count}个子目录）" if d.subdir_count else ""
            lines.append(f"| {status} [{label}]({link}) | {d.md_count} | {extra} |")
        lines.append("")

    return '\n'.join(lines)


def generate_readme_content(
    dir_path: Path,
    root: Path,
    doc_entries: list[DocEntry],
    dir_entries: list[DirEntry],
    custom_title: str | None = None,
) -> str:
    dir_name = dir_path.name
    default_title = humanize_dirname(dir_name)
    title = custom_title or default_title
    cat = infer_category(dir_path, root)
    doc_id = infer_id(dir_path, root)
    today = date.today().isoformat()

    index_tables = generate_index_tables(doc_entries, dir_entries)

    lines = []
    lines.append("---")
    lines.append(f'id: "{doc_id}"')
    lines.append(f'title: "{title}"')
    lines.append(f'category: "{cat}"')
    lines.append(f'date: "{today}"')
    lines.append("---")
    lines.append("")
    lines.append(f"# {title}")
    lines.append("")
    lines.append("> 本目录 README 由 `generate-readme.py` 自动生成，可根据需要补充概述和导航说明。")
    lines.append("")
    lines.append(README_INDEX_START)
    lines.append(index_tables)
    lines.append(README_INDEX_END)
    lines.append("")
    lines.append("## 🔗 相关资源")
    lines.append("")
    parent = dir_path.parent
    parent_readme = parent / 'README.md'
    if parent_readme.exists():
        try:
            parent_title = extract_title(parent_readme) or humanize_dirname(parent.name)
            lines.append(f"- [🏠 返回上级：{parent_title}](../README.md)")
        except Exception:
            lines.append(f"- [🏠 返回上级目录](../README.md)")
    try:
        depth_to_docs = len(dir_path.relative_to(root / 'docs').parts)
        docs_home = '../' * depth_to_docs + 'README.md'
        lines.append(f"- [📚 文档首页]({docs_home})")
    except ValueError:
        pass
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"<!-- generated by generate-readme.py on {today} -->")
    lines.append("")

    return '\n'.join(lines)


def find_missing_readmes(
    root: Path,
    start_path: Path | None = None,
    min_md_files: int = 1,
) -> list[Path]:
    search_root = start_path or (root / 'docs')
    missing = []

    for dirpath in sorted(search_root.rglob('*')):
        if not dirpath.is_dir():
            continue
        parts = set(dirpath.parts)
        if EXCLUDED_DIRS & parts:
            continue
        if '.git' in parts:
            continue
        readme = dirpath / 'README.md'
        if readme.exists():
            continue
        md_count = len(list(dirpath.glob('*.md')))
        if md_count >= min_md_files:
            missing.append(dirpath)

    return missing


def get_p1_dirs(root: Path) -> list[Path]:
    p1 = []
    docs = root / 'docs'

    p1_candidates = [
        docs / 'knowledge' / 'learning' / '04-docs-markup-tooling',
        docs / 'knowledge' / 'learning' / '05-ai-multimodal-content',
        docs / 'knowledge' / 'learning' / '06-business-trends-analysis',
        docs / 'knowledge' / 'learning' / '07-vendor-product-learning',
        docs / 'knowledge' / 'learning' / '08-systems-infrastructure',
        docs / 'knowledge' / 'learning' / 'okr-wiki',
        docs / 'retrospective' / 'assets',
        docs / 'retrospective' / 'templates',
        docs / 'superpowers' / 'plans',
        docs / 'superpowers' / 'specs',
    ]

    learning_01 = docs / 'knowledge' / 'learning' / '01-agent-protocols-interfaces'
    if learning_01.exists():
        for d in sorted(learning_01.iterdir()):
            if d.is_dir() and not d.name.startswith('.'):
                p1_candidates.append(d)

    learning_02 = docs / 'knowledge' / 'learning' / '02-agent-engineering-methodology'
    if learning_02.exists():
        for d in sorted(learning_02.iterdir()):
            if d.is_dir() and not d.name.startswith('.'):
                p1_candidates.append(d)

    learning_03 = docs / 'knowledge' / 'learning' / '03-agent-platforms-tools'
    if learning_03.exists():
        for d in sorted(learning_03.iterdir()):
            if d.is_dir() and not d.name.startswith('.'):
                p1_candidates.append(d)

    learning_04 = docs / 'knowledge' / 'learning' / '04-docs-markup-tooling'
    if learning_04.exists():
        for d in sorted(learning_04.iterdir()):
            if d.is_dir() and not d.name.startswith('.') and d.name not in ('04-docs-markup-tooling',):
                p1_candidates.append(d)

    learning_06 = docs / 'knowledge' / 'learning' / '06-business-trends-analysis'
    if learning_06.exists():
        for d in sorted(learning_06.iterdir()):
            if d.is_dir() and not d.name.startswith('.') and d.name not in ('06-business-trends-analysis',):
                p1_candidates.append(d)

    learning_07 = docs / 'knowledge' / 'learning' / '07-vendor-product-learning'
    if learning_07.exists():
        for d in sorted(learning_07.iterdir()):
            if d.is_dir() and not d.name.startswith('.') and d.name not in ('07-vendor-product-learning', 'openai'):
                p1_candidates.append(d)

    okr = docs / 'knowledge' / 'learning' / 'okr-wiki'
    if okr.exists():
        for d in sorted(okr.iterdir()):
            if d.is_dir() and not d.name.startswith('.'):
                p1_candidates.append(d)

    patterns_mp = docs / 'retrospective' / 'patterns' / 'methodology-patterns'
    if patterns_mp.exists():
        for d in sorted(patterns_mp.iterdir()):
            if d.is_dir() and not d.name.startswith('.'):
                readme = d / 'README.md'
                if not readme.exists():
                    p1_candidates.append(d)

    reports_ie = docs / 'retrospective' / 'reports' / 'insight-extraction'
    if reports_ie.exists():
        for d in sorted(reports_ie.iterdir()):
            if d.is_dir() and not d.name.startswith('.'):
                readme = d / 'README.md'
                if not readme.exists() and d.name not in ('external-learning', 'iot-ecosystem', 'meta-methodology', 'toolchain-dev'):
                    p1_candidates.append(d)

    reports_st = docs / 'retrospective' / 'reports' / 'standards-tools'
    if reports_st.exists():
        for d in sorted(reports_st.iterdir()):
            if d.is_dir() and not d.name.startswith('.'):
                readme = d / 'README.md'
                if not readme.exists():
                    p1_candidates.append(d)

    seen = set()
    for p in p1_candidates:
        if p.exists() and p.is_dir() and not (p / 'README.md').exists():
            rp = p.resolve()
            if rp not in seen:
                seen.add(rp)
                p1.append(p)

    return sorted(p1)


def generate_for_directory(
    dir_path: Path,
    root: Path,
    dry_run: bool = False,
    force: bool = False,
    custom_title: str | None = None,
) -> tuple[bool, str]:
    readme_path = dir_path / 'README.md'

    if readme_path.exists() and not force:
        return False, f"已存在，跳过（使用 --force 覆盖）"

    doc_entries, dir_entries = scan_directory(dir_path, root)

    if not doc_entries and not dir_entries:
        return False, "目录为空，跳过"

    content = generate_readme_content(dir_path, root, doc_entries, dir_entries, custom_title)

    if dry_run:
        rel = dir_path.relative_to(root)
        print()
        print_header(f"预览: {rel / 'README.md'}")
        print(content)
        return True, "预览完成"

    readme_path.write_text(content, encoding='utf-8')
    return True, f"已生成（{len(doc_entries)}个文档，{len(dir_entries)}个子目录）"


def find_generated_readmes(root: Path, start_path: Path | None = None) -> list[Path]:
    search_root = start_path or (root / 'docs')
    results = []
    for readme in sorted(search_root.rglob('README.md')):
        parts = set(readme.parts)
        if EXCLUDED_DIRS & parts:
            continue
        try:
            content = readme.read_text(encoding='utf-8')
        except (OSError, UnicodeDecodeError):
            continue
        if GENERATED_FOOTER_PREFIX in content:
            results.append(readme)
    return results


def upgrade_readme_markers(readme_path: Path, root: Path) -> bool:
    dir_path = readme_path.parent
    content = readme_path.read_text(encoding='utf-8')

    if README_INDEX_START in content and README_INDEX_END in content:
        return False

    doc_entries, dir_entries = scan_directory(dir_path, root)
    index_tables = generate_index_tables(doc_entries, dir_entries)

    marker_block = f"{README_INDEX_START}\n{index_tables}\n{README_INDEX_END}"

    doc_idx_pos = content.find("## 📄 文档索引")
    dir_nav_pos = content.find("## 📁 子目录导航")
    resources_pos = content.find("## 🔗 相关资源")

    if doc_idx_pos != -1 and resources_pos != -1:
        new_content = (
            content[:doc_idx_pos]
            + marker_block
            + "\n\n"
            + content[resources_pos:]
        )
        readme_path.write_text(new_content, encoding='utf-8')
        return True

    if doc_idx_pos == -1 and dir_nav_pos == -1 and resources_pos != -1:
        new_content = (
            content[:resources_pos]
            + marker_block
            + "\n\n"
            + content[resources_pos:]
        )
        readme_path.write_text(new_content, encoding='utf-8')
        return True

    return False


def update_readme_index(
    readme_path: Path,
    root: Path,
    dry_run: bool = False,
) -> tuple[bool, str]:
    if not readme_path.exists():
        return False, "README 不存在"

    content = readme_path.read_text(encoding='utf-8')

    has_markers = README_INDEX_START in content and README_INDEX_END in content
    has_footer = GENERATED_FOOTER_PREFIX in content

    if not has_markers:
        if has_footer:
            if dry_run:
                return True, "需要升级标记（将添加START/END标记）"
            upgraded = upgrade_readme_markers(readme_path, root)
            if not upgraded:
                return False, "无法自动升级标记区域（未找到插入位置）"
            content = readme_path.read_text(encoding='utf-8')
        else:
            return False, "非脚本生成的README，跳过"

    dir_path = readme_path.parent
    doc_entries, dir_entries = scan_directory(dir_path, root)
    new_index = generate_index_tables(doc_entries, dir_entries)

    if not new_index.strip():
        new_index = "_暂无文档_"

    start_marker_end = content.find(README_INDEX_START) + len(README_INDEX_START)
    end_marker_start = content.find(README_INDEX_END)
    old_index = content[start_marker_end:end_marker_start].strip()

    if old_index == new_index.strip():
        return True, f"索引已是最新（{len(doc_entries)}个文档，{len(dir_entries)}个子目录）"

    if dry_run:
        rel = dir_path.relative_to(root)
        print()
        print_header(f"将更新: {rel / 'README.md'}")
        print(f"  文档: {len(doc_entries)}个, 子目录: {len(dir_entries)}个")
        return True, f"将更新（{len(doc_entries)}个文档，{len(dir_entries)}个子目录）"

    update_marker_region(readme_path, README_INDEX_START, README_INDEX_END, new_index)

    today = date.today().isoformat()
    updated_content = readme_path.read_text(encoding='utf-8')
    old_date_pattern = re.compile(
        r'<!-- generated by generate-readme\.py on \d{4}-\d{2}-\d{2} -->'
    )
    new_footer = f"<!-- generated by generate-readme.py on {today} -->"
    if old_date_pattern.search(updated_content):
        updated_content = old_date_pattern.sub(new_footer, updated_content, count=1)
    else:
        updated_content = updated_content.rstrip() + "\n\n" + new_footer + "\n"
    readme_path.write_text(updated_content, encoding='utf-8')

    return True, f"已更新（{len(doc_entries)}个文档，{len(dir_entries)}个子目录）"


def cmd_update(args) -> int:
    root = args.path or resolve_project_root(__file__)

    targets = []
    if args.target_dir:
        tp = Path(args.target_dir).resolve()
        if tp.is_file() and tp.name == 'README.md':
            targets = [tp]
        elif tp.is_dir():
            targets = [tp / 'README.md']
        else:
            print_error(f"目标路径无效: {args.target_dir}")
            return 1
    else:
        targets = find_generated_readmes(root)
        print(f"更新模式：发现 {len(targets)} 个由脚本生成的 README")

    success = 0
    skipped = 0
    failed = 0
    upgraded = 0

    for readme in targets:
        try:
            dir_path = readme.parent
            ok, msg = update_readme_index(readme, root, dry_run=args.dry_run)
            try:
                rel = dir_path.relative_to(root)
            except ValueError:
                rel = dir_path
            if ok:
                if "升级" in msg or "添加" in msg:
                    upgraded += 1
                print_pass(f"  {rel}: {msg}")
                success += 1
            else:
                print_warn(f"  {rel}: {msg}")
                skipped += 1
        except Exception as e:
            print_error(f"  {readme}: 失败 - {e}")
            failed += 1

    print()
    if args.dry_run:
        print(f"预览完成：{success} 个将更新，{skipped} 个跳过，{failed} 个失败"
              + (f"，{upgraded} 个需要升级标记" if upgraded else ""))
    else:
        print(f"执行完成：{success} 个成功，{skipped} 个跳过，{failed} 个失败"
              + (f"，{upgraded} 个已升级标记" if upgraded else ""))

    return 0 if failed == 0 else 1


def cmd_scan(args) -> int:
    root = args.path or resolve_project_root(__file__)
    missing = find_missing_readmes(root, min_md_files=args.min_files)
    print(f"扫描结果：共发现 {len(missing)} 个目录缺失 README（含至少 {args.min_files} 个.md文件）")
    print()
    for d in missing:
        rel = d.relative_to(root)
        md_count = len(list(d.glob('*.md')))
        subdirs = len([x for x in d.iterdir() if x.is_dir() and not x.name.startswith('.')])
        print(f"  {rel} - {md_count}个md, {subdirs}个子目录")
    return 0


def cmd_generate(args) -> int:
    root = args.path or resolve_project_root(__file__)

    targets = []
    if args.target_dir:
        targets = [Path(args.target_dir).resolve()]
    elif args.p1:
        targets = get_p1_dirs(root)
        print(f"P1 阶段：共 {len(targets)} 个待处理目录")
    elif args.all:
        targets = find_missing_readmes(root, min_md_files=args.min_files)
        print(f"全部模式：共 {len(targets)} 个待处理目录")
    else:
        print_error("请指定目标：--path <dir> / --p1 / --all / --scan")
        return 1

    success = 0
    skipped = 0
    failed = 0

    for target in targets:
        try:
            ok, msg = generate_for_directory(
                target, root,
                dry_run=args.dry_run,
                force=args.force,
                custom_title=args.title,
            )
            try:
                rel = target.relative_to(root)
            except ValueError:
                rel = target
            if ok:
                print_pass(f"  {rel}: {msg}")
                success += 1
            else:
                print_warn(f"  {rel}: {msg}")
                skipped += 1
        except Exception as e:
            print_error(f"  {target}: 失败 - {e}")
            failed += 1

    print()
    if args.dry_run:
        print(f"预览完成：{success} 个目录将生成，{skipped} 个跳过，{failed} 个失败")
    else:
        print(f"执行完成：{success} 个成功，{skipped} 个跳过，{failed} 个失败")

    return 0 if failed == 0 else 1


def main():
    setup_safe_output()
    parser = argparse.ArgumentParser(description='目录 README 自动生成与索引更新工具')
    parser.add_argument('--path', type=Path, default=None, help='项目根目录路径（默认自动解析）')
    parser.add_argument('--dry-run', action='store_true', help='预览模式，不写入文件')
    parser.add_argument('--force', action='store_true', help='强制覆盖已存在的 README')
    parser.add_argument('--title', type=str, default=None, help='自定义目录标题（单目录模式下使用）')
    parser.add_argument('--min-files', type=int, default=1, help='最小md文件数（仅对--all/--scan生效）')

    group = parser.add_mutually_exclusive_group(required=False)
    group.add_argument('--scan', action='store_true', help='仅扫描缺失 README 的目录')
    group.add_argument('--p1', action='store_true', help='批量处理 P1 阶段内容聚合目录')
    group.add_argument('--all', action='store_true', help='处理所有缺失 README 的目录')
    group.add_argument('--update', action='store_true', help='增量更新已有README的索引表（自动升级旧标记）')
    parser.add_argument('--target-dir', type=str, default=None,
                        help='指定目标目录（生成模式为该目录生成README；更新模式配合--update更新该目录）')

    args = parser.parse_args()

    has_action = args.scan or args.update or args.p1 or args.all or args.target_dir
    if not has_action:
        parser.print_help()
        return 1

    if args.scan:
        return cmd_scan(args)
    elif args.update:
        return cmd_update(args)
    else:
        return cmd_generate(args)


if __name__ == "__main__":
    sys.exit(main())
