"""Jest测试骨架生成器。

为Web API Profile生成Jest测试文件（JavaScript/TypeScript），
使用axios作为HTTP客户端，包含正常场景、边界值和错误场景三类测试用例。
"""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[2]
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from mdi.models import MDIDocument, Interface, Parameter
from mdi.generators.base import BaseGenerator
from mdi.generators.utils import (
    make_interface_name,
    sanitize_identifier,
)
from mdi.mock_data import generate_mock_value, generate_edge_value


class JestGenerator(BaseGenerator):
    """Jest测试骨架生成器。"""

    def _generate(self, doc: MDIDocument, output_dir: Path) -> list[Path]:
        generated_files: list[Path] = []
        module_name = sanitize_identifier(
            doc.frontmatter.get("name", "test_api")
        ).replace("-", "_")
        test_filename = f"{module_name}.test.js"

        content = self._generate_test_module(doc)
        test_path = output_dir / test_filename
        generated_files.append(self._write_file(test_path, content))

        config_path = output_dir / "jest.config.js"
        if not config_path.exists():
            generated_files.append(self._write_file(config_path, self._generate_jest_config()))

        return generated_files

    def _generate_test_module(self, doc: MDIDocument) -> str:
        lines: list[str] = []
        title = doc.title or doc.frontmatter.get("name", "API")
        base_url = doc.frontmatter.get("baseUrl", doc.frontmatter.get("baseurl", "https://api.example.com"))

        lines.append("/**")
        lines.append(f" * Jest tests for {title}.")
        lines.append(" * Auto-generated by MDI.")
        lines.append(" */")
        lines.append("")
        lines.append("const axios = require('axios');")
        lines.append("")
        lines.append(f"const BASE_URL = process.env.API_BASE_URL || '{base_url}';")
        lines.append("const API_TOKEN = process.env.API_TOKEN || null;")
        lines.append("")
        lines.append("const apiClient = axios.create({")
        lines.append("  baseURL: BASE_URL,")
        lines.append("  headers: {")
        lines.append("    'Content-Type': 'application/json',")
        lines.append("    ...(API_TOKEN && { 'Authorization': `Bearer ${API_TOKEN}` }),")
        lines.append("  },")
        lines.append("});")
        lines.append("")

        if not doc.interfaces:
            lines.append("// TODO: 未发现接口定义，请检查MDI文档")
            lines.append("test('placeholder', () => {")
            lines.append("  expect(true).toBe(true);")
            lines.append("});")
            lines.append("")
            return "\n".join(lines)

        for iface in doc.interfaces:
            lines.extend(self._generate_interface_tests(iface))

        return "\n".join(lines)

    def _generate_interface_tests(self, iface: Interface) -> list[str]:
        lines: list[str] = []
        method = iface.method.upper()
        desc_name = iface.summary or f"{method} {iface.path}"

        path_params = [p for p in iface.parameters if p.location == "path"]
        query_params = [p for p in iface.parameters if p.location == "query"]
        body_params = [p for p in iface.parameters if p.location not in ("path", "query", "header", "cookie")]
        func_prefix = self._func_prefix(iface)

        ctx = _TestContext(iface.path, method, path_params, query_params, body_params, iface=iface)

        lines.append(f"// Tests for {method} {iface.path} - {desc_name}")
        lines.append(f"describe('{method} {iface.path}', () => {{")

        lines.extend(self._test_success(ctx, func_prefix))
        lines.extend(self._test_missing_required(ctx, func_prefix))
        lines.extend(self._test_invalid_params(ctx, func_prefix))
        lines.extend(self._test_error_codes(ctx, func_prefix))

        lines.append("});")
        lines.append("")
        return lines

    def _build_url_and_args(self, ctx: "_TestContext", override: dict[str, object], skip: set[str]) -> tuple[str, str, str]:
        path_values: dict[str, object] = {}
        query_obj: dict[str, object] = {}
        body_obj: dict[str, object] = {}

        for p in ctx.path_params:
            val = override.get(p.name, generate_mock_value(p))
            path_values[p.name] = val

        url = ctx.path
        for name, val in path_values.items():
            url = url.replace("{" + name + "}", str(val))

        for p in ctx.query_params:
            if p.name in skip:
                continue
            val = override.get(p.name, generate_mock_value(p))
            query_obj[p.name] = val

        has_body = ctx.method not in ("GET", "DELETE", "HEAD")
        if has_body:
            for p in ctx.body_params:
                if p.name in skip:
                    continue
                if not p.required and p.name not in override:
                    continue
                val = override.get(p.name, generate_mock_value(p))
                body_obj[p.name] = val

        query_js = self._js_repr(query_obj) if query_obj else "undefined"
        body_js = self._js_repr(body_obj) if body_obj else "undefined"
        return url, query_js, body_js

    def _request_line(self, method: str, url_expr: str, query_expr: str, body_expr: str) -> str:
        m = method.lower()
        if m in ("get", "delete", "head", "options"):
            return f"    const response = await apiClient.{m}({url_expr}, {{ params: {query_expr} }});"
        else:
            return f"    const response = await apiClient.{m}({url_expr}, {body_expr}, {{ params: {query_expr} }});"

    def _test_success(self, ctx: "_TestContext", prefix: str) -> list[str]:
        indent = "  "
        success_code = self._success_code(ctx.iface)
        url, qs, body = self._build_url_and_args(ctx, {}, set())

        lines = [
            f"{indent}test('{prefix}_success', async () => {{",
            f"{indent}  // 正常场景：请求成功返回{success_code}",
            f"{indent}  const url = '{url}';",
            self._request_line(ctx.method, "url", qs, body),
            f"{indent}  expect(response.status).toBe({success_code});",
            f"{indent}}});",
            "",
        ]
        return lines

    def _test_missing_required(self, ctx: "_TestContext", prefix: str) -> list[str]:
        indent = "  "
        lines: list[str] = []
        required_body = [p for p in ctx.body_params if p.required]
        required_query = [p for p in ctx.query_params if p.required]

        for miss_p in required_body + required_query:
            safe_name = self._var_name(miss_p.name)
            loc_desc = "body" if miss_p in required_body else "query"
            url, qs, body = self._build_url_and_args(ctx, {}, {miss_p.name})
            lines.append(f"{indent}test('{prefix}_missing_{safe_name}', async () => {{")
            lines.append(f"{indent}  // 错误场景：缺少必填参数{miss_p.name}（{loc_desc}），期望400")
            lines.append(f"{indent}  const url = '{url}';")
            lines.append(self._request_line(ctx.method, "url", qs, body))
            lines.append(f"{indent}  expect(response.status).toBe(400);")
            lines.append(f"{indent}}});")
            lines.append("")

        return lines

    def _test_invalid_params(self, ctx: "_TestContext", prefix: str) -> list[str]:
        indent = "  "
        lines: list[str] = []
        str_required = [p for p in ctx.all_required if (p.type or "string").lower() in ("string", "str", "")]
        int_required = [p for p in ctx.all_required if (p.type or "").lower() in ("integer", "int")]

        for p in str_required:
            safe_name = self._var_name(p.name)
            url, qs, body = self._build_url_and_args(ctx, {p.name: generate_edge_value(p, "empty")}, set())
            lines.append(f"{indent}test('{prefix}_empty_{safe_name}', async () => {{")
            lines.append(f"{indent}  // 边界值：{p.name}为空字符串，期望400")
            lines.append(f"{indent}  const url = '{url}';")
            lines.append(self._request_line(ctx.method, "url", qs, body))
            lines.append(f"{indent}  expect(response.status).toBe(400);")
            lines.append(f"{indent}}});")
            lines.append("")

        for p in int_required:
            safe_name = self._var_name(p.name)
            url, qs, body = self._build_url_and_args(ctx, {p.name: generate_edge_value(p, "negative")}, set())
            lines.append(f"{indent}test('{prefix}_negative_{safe_name}', async () => {{")
            lines.append(f"{indent}  // 边界值：{p.name}为负数，期望400")
            lines.append(f"{indent}  const url = '{url}';")
            lines.append(self._request_line(ctx.method, "url", qs, body))
            lines.append(f"{indent}  expect(response.status).toBe(400);")
            lines.append(f"{indent}}});")
            lines.append("")

        return lines

    def _test_error_codes(self, ctx: "_TestContext", prefix: str) -> list[str]:
        indent = "  "
        lines: list[str] = []

        for err in ctx.iface.errors:
            err_code = int(err.code)
            if err_code == 400:
                continue
            err_msg = self._var_name(str(err.message)) if err.message else f"err_{err_code}"
            desc = err.description or err.message or f"错误码{err_code}"
            url, qs, body = self._build_url_and_args(ctx, {}, set())
            lines.append(f"{indent}test('{prefix}_{err_msg}', async () => {{")
            lines.append(f"{indent}  // TODO: 构造触发{err.code} {err.message}的请求数据")
            lines.append(f"{indent}  // 错误场景：{desc}（{err_code}）")
            lines.append(f"{indent}  const url = '{url}';")
            lines.append(self._request_line(ctx.method, "url", qs, body))
            lines.append(f"{indent}  expect(response.status).toBe({err_code});")
            lines.append(f"{indent}}});")
            lines.append("")

        return lines

    def _generate_jest_config(self) -> str:
        return (
            "/**\n"
            " * Jest configuration for MDI-generated API tests.\n"
            " */\n"
            "module.exports = {\n"
            "  testEnvironment: 'node',\n"
            "  testMatch: ['**/*.test.js'],\n"
            "  testTimeout: 10000,\n"
            "};\n"
        )

    def _func_prefix(self, iface: Interface) -> str:
        method = iface.method.lower()
        name = sanitize_identifier(iface.name or iface.path).replace("-", "_")
        if name.startswith("_"):
            name = name[1:]
        return f"{method}_{name}"

    def _var_name(self, name: str) -> str:
        return sanitize_identifier(name).replace("-", "_")

    def _success_code(self, iface: Interface) -> int:
        for r in iface.responses:
            code = int(r.status_code)
            if 200 <= code < 300:
                return code
        m = iface.method.upper()
        if m == "POST":
            return 201
        if m == "DELETE":
            return 204
        return 200

    @staticmethod
    def _js_repr(val: object) -> str:
        if val is None:
            return "null"
        if isinstance(val, bool):
            return "true" if val else "false"
        if isinstance(val, (int, float)):
            return str(val)
        if isinstance(val, str):
            escaped = val.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
            return f"'{escaped}'"
        if isinstance(val, list):
            return "[" + ", ".join(JestGenerator._js_repr(v) for v in val) + "]"
        if isinstance(val, dict):
            items = ", ".join(
                f"{JestGenerator._js_repr(k)}: {JestGenerator._js_repr(v)}"
                for k, v in val.items()
            )
            return "{" + items + "}"
        return repr(val)


class _TestContext:
    """测试生成上下文。"""

    def __init__(
        self,
        path: str,
        method: str,
        path_params: list[Parameter],
        query_params: list[Parameter],
        body_params: list[Parameter],
        iface: Interface | None = None,
    ) -> None:
        self.path = path
        self.method = method
        self.path_params = path_params
        self.query_params = query_params
        self.body_params = body_params
        self.iface = iface

    @property
    def all_required(self) -> list[Parameter]:
        return [p for p in self.path_params + self.query_params + self.body_params if p.required]
