title = "Roles行内扩展示例"
category = "learning"
tags = ["myst","examples","roles","inline","abbr","subscript","superscript","math"]
date = "2026-07-02"
version = "1.0"
source = "https://mystmd.org/guide/roles"
