# html-deck :: new-deck.ps1 — scaffold a new deck directory
#
# Usage:
#   new-deck.ps1 <name> <output-base-dir>
#
# Creates <output-base-dir>/<name>/ with:
#   <name>.html        (scaffold with <!-- Generated by Trae Work --> comment)
#   assets/            (for generated/downloaded images, chart JS)
#   _shared/           (minimal shared assets — model copies more as needed)
#     ├── base.css
#     ├── fonts.css
#     ├── decorations.css
#     ├── runtime.js
#     ├── echarts.min.js
#     ├── echarts-theme-sync.js
#     ├── animations/
#     │   ├── animations.css
#     │   ├── fx-runtime.js
#     │   └── fx/          (empty — model copies needed fx scripts)
#     └── themes/           (empty — model copies needed themes)

param(
    [string]$Name,
    [string]$BaseDir
)

if (-not $Name -or -not $BaseDir) {
    Write-Error "usage: new-deck.ps1 <name> <output-base-dir>"
    Write-Error ""
    Write-Error "  <name>            Deck directory name (also used as HTML filename)"
    Write-Error "  <output-base-dir> Directory where <name>/ will be created (your work dir)"
    exit 1
}

$HERE = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)

# Resolve base dir to absolute path
if (-not [System.IO.Path]::IsPathRooted($BaseDir)) {
    $BaseDir = Join-Path (Get-Location) $BaseDir
}

$OUT_DIR = Join-Path $BaseDir $Name
if (Test-Path $OUT_DIR) {
    Write-Error "error: $OUT_DIR already exists"
    exit 1
}

# --- Create directory structure ---
New-Item -ItemType Directory -Path (Join-Path $OUT_DIR "assets") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $OUT_DIR "_shared\animations\fx") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $OUT_DIR "_shared\themes") -Force | Out-Null

# --- Copy minimal shared assets ---
foreach ($f in @("base.css", "fonts.css", "decorations.css", "runtime.js", "echarts.min.js", "echarts-theme-sync.js", "chart.umd.min.js")) {
    $src = Join-Path $HERE "assets\$f"
    if (Test-Path $src) {
        Copy-Item $src (Join-Path $OUT_DIR "_shared\$f")
    }
}

# Copy highlight.js assets
$hljsDir = Join-Path $HERE "assets\hljs"
if (Test-Path $hljsDir) {
    $hljsOut = Join-Path $OUT_DIR "_shared\hljs"
    New-Item -ItemType Directory -Path $hljsOut -Force | Out-Null
    Copy-Item (Join-Path $hljsDir "*") $hljsOut
}

# Copy animations base files
foreach ($f in @("animations.css", "fx-runtime.js")) {
    $src = Join-Path $HERE "assets\animations\$f"
    if (Test-Path $src) {
        Copy-Item $src (Join-Path $OUT_DIR "_shared\animations\$f")
    }
}

# --- Generate scaffold HTML ---
$HTML_CONTENT = @'
<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh-CN" data-theme="minimal-white">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-content-type" content="presentation" />
<meta name="x-presentation-version" content="1.0" />
<meta name="x-presentation-indicator" content="deck-stage .slide" />
<title>Deck</title>
<link rel="stylesheet" href="./_shared/fonts.css">
<link rel="stylesheet" href="./_shared/base.css">
<link id="theme-link" rel="stylesheet" href="./_shared/themes/minimal-white.css">
<link rel="stylesheet" href="./_shared/animations/animations.css">
<!-- <link rel="stylesheet" href="./_shared/decorations.css"> -->
</head>
<body data-themes="minimal-white" data-theme-base="./_shared/themes/">
<deck-stage width="1920" height="1080">

  <!-- 1. Cover -->
  <section class="slide active" data-deck-label="Cover">
    <p class="kicker">Deck · 2026</p>
    <h1 class="h1 anim-fade-up" data-anim="fade-up">Presentation Title</h1>
    <p class="lede">Subtitle goes here</p>
    <div class="deck-footer"><span class="dim2">Author</span><span class="slide-number" data-current="1" data-total="3"></span></div>
    <div class="notes">Speaker notes go here.</div>
  </section>

  <!-- 2. Content -->
  <section class="slide" data-deck-label="Content">
    <p class="kicker">Section</p>
    <h2 class="h2">Slide Title</h2>
    <p>Content goes here.</p>
  </section>

  <!-- 3. Thanks -->
  <section class="slide center tc" data-deck-label="Thanks">
    <h1 class="h1" style="font-size:160px;line-height:1"><span class="gradient-text">Thanks</span></h1>
  </section>

</deck-stage>
<script src="./_shared/runtime.js"></script>
<script src="./_shared/echarts-theme-sync.js"></script>
<!-- <script src="./_shared/animations/fx-runtime.js"></script> -->
</body></html>
'@

$HTML_FILE = Join-Path $OUT_DIR "$Name.html"
[System.IO.File]::WriteAllText($HTML_FILE, $HTML_CONTENT, [System.Text.Encoding]::UTF8)

Write-Host "OK Created: $HTML_FILE"
Write-Host "OK Created: $(Join-Path $OUT_DIR 'assets\')"
Write-Host "OK Created: $(Join-Path $OUT_DIR '_shared\') (base.css, fonts.css, runtime.js, animations/)"
Write-Host "OK Created: $(Join-Path $OUT_DIR '_shared\themes\') (copy needed themes here from $HERE\assets\themes\)"
Write-Host "OK Created: $(Join-Path $OUT_DIR '_shared\animations\fx\') (copy needed fx here from $HERE\assets\animations\fx\)"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Copy theme:  Copy-Item $HERE\assets\themes\<theme>.css $OUT_DIR\_shared\themes\"
Write-Host "  2. Copy fx:     Copy-Item $HERE\assets\animations\fx\<effect>.js $OUT_DIR\_shared\animations\fx\"
Write-Host "  3. Edit $Name.html — fill in theme, content, animations"
Write-Host "  4. Place images in $OUT_DIR\assets\"
