#!/usr/bin/env bash
# html-deck :: new-deck.sh — scaffold a new deck directory
#
# Usage:
#   new-deck.sh <name> <output-base-dir>
#
# Creates <output-base-dir>/<name>/ with:
#   <name>.html        (scaffold with <!-- Generated by Trae Work --> comment)
#   assets/            (for generated/downloaded images, chart JS)
#   _shared/           (minimal shared assets — model copies more as needed)
#     ├── base.css
#     ├── fonts.css
#     ├── decorations.css
#     ├── runtime.js
#     ├── echarts-theme-sync.js
#     ├── animations/
#     │   ├── animations.css
#     │   ├── fx-runtime.js
#     │   └── fx/          (empty — model copies needed fx scripts)
#     └── themes/           (empty — model copies needed themes)

set -euo pipefail

NAME="${1:-}"
BASE_DIR="${2:-}"

if [[ -z "$NAME" || -z "$BASE_DIR" ]]; then
  echo "usage: new-deck.sh <name> <output-base-dir>" >&2
  echo "" >&2
  echo "  <name>            Deck directory name (also used as HTML filename)" >&2
  echo "  <output-base-dir> Directory where <name>/ will be created (your work dir)" >&2
  exit 1
fi

HERE="$(cd "$(dirname "$0")/.." && pwd)"

# Resolve base dir
if [[ "$BASE_DIR" != /* ]]; then
  BASE_DIR="$PWD/$BASE_DIR"
fi

OUT_DIR="$BASE_DIR/$NAME"
if [[ -e "$OUT_DIR" ]]; then
  echo "error: $OUT_DIR already exists" >&2
  exit 1
fi

# --- Create directory structure ---
mkdir -p "$OUT_DIR/assets" \
         "$OUT_DIR/_shared/animations/fx" \
         "$OUT_DIR/_shared/themes"

# --- Copy minimal shared assets ---
for f in base.css fonts.css decorations.css runtime.js echarts.min.js echarts-theme-sync.js chart.umd.min.js; do
  if [[ -f "$HERE/assets/$f" ]]; then
    cp "$HERE/assets/$f" "$OUT_DIR/_shared/"
  fi
done

# Copy animations base files
for f in animations.css fx-runtime.js; do
  if [[ -f "$HERE/assets/animations/$f" ]]; then
    cp "$HERE/assets/animations/$f" "$OUT_DIR/_shared/animations/"
  fi
done

# Copy highlight.js assets
if [[ -d "$HERE/assets/hljs" ]]; then
  mkdir -p "$OUT_DIR/_shared/hljs"
  cp "$HERE/assets/hljs/"* "$OUT_DIR/_shared/hljs/"
fi

# --- Generate scaffold HTML ---
cat > "$OUT_DIR/$NAME.html" << 'HTML'
<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh-CN" data-theme="minimal-white">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-content-type" content="presentation" />
<meta name="x-presentation-version" content="1.0" />
<meta name="x-presentation-indicator" content="deck-stage .slide" />
<title>Deck</title>
<link rel="stylesheet" href="./_shared/fonts.css">
<link rel="stylesheet" href="./_shared/base.css">
<link id="theme-link" rel="stylesheet" href="./_shared/themes/minimal-white.css">
<link rel="stylesheet" href="./_shared/animations/animations.css">
<!-- <link rel="stylesheet" href="./_shared/decorations.css"> -->
</head>
<body data-themes="minimal-white" data-theme-base="./_shared/themes/">
<deck-stage width="1920" height="1080">

  <!-- 1. Cover -->
  <section class="slide" data-deck-label="Cover">
    <p class="kicker">Deck · 2026</p>
    <h1 class="h1 anim-fade-up" data-anim="fade-up">Presentation Title</h1>
    <p class="lede">Subtitle goes here</p>
    <div class="deck-footer"><span class="dim2">Author</span><span class="slide-number" data-current="1" data-total="3"></span></div>
    <div class="notes">Speaker notes go here.</div>
  </section>

  <!-- 2. Content -->
  <section class="slide" data-deck-label="Content">
    <p class="kicker">Section</p>
    <h2 class="h2">Slide Title</h2>
    <p>Content goes here.</p>
  </section>

  <!-- 3. Thanks -->
  <section class="slide center tc" data-deck-label="Thanks">
    <h1 class="h1" style="font-size:160px;line-height:1"><span class="gradient-text">Thanks</span></h1>
  </section>

</deck-stage>
<script src="./_shared/runtime.js"></script>
<script src="./_shared/echarts-theme-sync.js"></script>
<!-- <script src="./_shared/animations/fx-runtime.js"></script> -->
</body></html>
HTML

echo "✔ Created: $OUT_DIR/$NAME.html"
echo "✔ Created: $OUT_DIR/assets/"
echo "✔ Created: $OUT_DIR/_shared/ (base.css, fonts.css, runtime.js, animations/)"
echo "✔ Created: $OUT_DIR/_shared/themes/ (copy needed themes here from $HERE/assets/themes/)"
echo "✔ Created: $OUT_DIR/_shared/animations/fx/ (copy needed fx here from $HERE/assets/animations/fx/)"
echo ""
echo "Next steps:"
echo "  1. Copy theme:  cp $HERE/assets/themes/<theme>.css $OUT_DIR/_shared/themes/"
echo "  2. Copy fx:     cp $HERE/assets/animations/fx/<effect>.js $OUT_DIR/_shared/animations/fx/"
echo "  3. Edit $NAME.html — fill in theme, content, animations"
echo "  4. Place images in $OUT_DIR/assets/"
