id = "docs-knowledge-learning-06-business-trends-analysis-papi-jiang-solo-ip-trend-wiki-index"
title = "Papi酱单人IP趋势分析"
category = "knowledge/learning/06-business-trends-analysis/papi-jiang-solo-ip-trend-wiki"
date = "2026-07-02"
version = "1.0"
