# html-report :: new-report.ps1 — scaffold a new report directory
#
# Usage:
#   new-report.ps1 <name> <output-base-dir>
#
# Creates <output-base-dir>/<name>/ with:
#   <name>.html        (scaffold with <!-- Generated by Trae Work --> comment)
#   assets/            (for generated/downloaded images)
#   _shared/js/        (pre-populated with JS libraries)
#   _shared/fonts/     (empty, model copies needed fonts here)

param(
    [string]$Name,
    [string]$BaseDir
)

if (-not $Name -or -not $BaseDir) {
    Write-Error "usage: new-report.ps1 <name> <output-base-dir>"
    Write-Error ""
    Write-Error "  <name>            Report directory name (also used as HTML filename)"
    Write-Error "  <output-base-dir> Directory where <name>/ will be created (your work dir)"
    exit 1
}

$HERE = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)

# Resolve base dir to absolute path
if (-not [System.IO.Path]::IsPathRooted($BaseDir)) {
    $BaseDir = Join-Path (Get-Location) $BaseDir
}

$OUT_DIR = Join-Path $BaseDir $Name
if (Test-Path $OUT_DIR) {
    Write-Error "error: $OUT_DIR already exists"
    exit 1
}

# --- Create directory structure ---
New-Item -ItemType Directory -Path (Join-Path $OUT_DIR "assets") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $OUT_DIR "_shared\js") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $OUT_DIR "_shared\fonts") -Force | Out-Null

# --- Generate scaffold HTML ---
$HTML_CONTENT = @'
<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Report</title>

  <style>
    /* === Font faces — filled by agent per chosen theme === */
    /*
    @font-face {
      font-family: 'FontName';
      src: url('./_shared/fonts/FontName-Regular.ttf') format('truetype');
      font-weight: 400;
    }
    @font-face {
      font-family: 'FontName';
      src: url('./_shared/fonts/FontName-Bold.ttf') format('truetype');
      font-weight: 700;
    }
    @font-face {
      font-family: 'MonoName';
      src: url('./_shared/fonts/MonoName-Regular.ttf') format('truetype');
      font-weight: 400;
    }
    */
  </style>

  <style>
    /* === Theme CSS variables === */
    :root {
      --bg: #ffffff;
      --bg2: #f5f5f5;
      --ink: #1a1a1a;
      --muted: #6b7280;
      --rule: #e5e7eb;
      --accent: #2563eb;
      --accent2: #7c3aed;
      --font: 'FontName', serif;
      --font-mono: 'MonoName', monospace;
      --max: 860px;
    }

    /* === Base styles === */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { font-size: 16px; scroll-behavior: smooth; }
    body {
      font-family: var(--font);
      color: var(--ink);
      background: var(--bg);
      line-height: 1.7;
      padding: 2rem 1rem;
    }
    article.page {
      max-width: var(--max);
      margin: 0 auto;
    }
  </style>
</head>
<body>
  <article class="page">
    <header>
      <h1>Report Title</h1>
    </header>
    <main>
      <section>
        <h2>Section 1</h2>
        <p>Content goes here.</p>
      </section>
    </main>
    <footer>
      <div class="sources">
        <h2>Sources</h2>
        <ol></ol>
      </div>
    </footer>
  </article>

  <!-- Shared JS — uncomment what you need -->
  <!-- <script src="./_shared/js/echarts.min.js"></script> -->
  <!-- <script src="./_shared/js/mermaid.min.js"></script> -->
  <!-- <script src="./assets/charts.js"></script> -->
  <!-- <script src="./_shared/js/lightbox.js"></script> -->
</body>
</html>
'@

$HTML_FILE = Join-Path $OUT_DIR "$Name.html"
[System.IO.File]::WriteAllText($HTML_FILE, $HTML_CONTENT, [System.Text.Encoding]::UTF8)

Write-Host "OK Created: $HTML_FILE"
Write-Host "OK Created: $(Join-Path $OUT_DIR 'assets\')"
Write-Host "OK Created: $(Join-Path $OUT_DIR '_shared\js\') (copy needed JS here from $HERE\assets\js\)"
Write-Host "OK Created: $(Join-Path $OUT_DIR '_shared\fonts\') (copy needed fonts here from $HERE\canvas-fonts\)"
