# Stage 6: Create non-admin user devuser + configure directories + entrypoint setup

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

Write-Host "[BUILD] Creating non-admin user 'devuser'..."

$userName = "devuser"
$userPassword = ConvertTo-SecureString "devcontainer" -AsPlainText -Force

# Check if user exists, create if not
$existingUser = Get-LocalUser -Name $userName -ErrorAction SilentlyContinue
if (-not $existingUser) {
    New-LocalUser -Name $userName `
        -Password $userPassword `
        -Description "DevContainer non-admin user" `
        -FullName "Dev User" `
        -UserMayNotChangePassword $false `
        -PasswordNeverExpires $true `
        -AccountNeverExpires | Out-Null
    Write-Host "[OK] User 'devuser' created"
} else {
    Write-Host "[INFO] User 'devuser' already exists, ensuring configuration..."
}

# Ensure user is NOT in Administrators group
$adminGroup = [ADSI]"WinNT://./Administrators,group"
$userAdsPath = "WinNT://$env:COMPUTERNAME/$userName,user"
try {
    $adminGroup.Remove($userAdsPath)
    Write-Host "[OK] Removed devuser from Administrators group (non-admin enforced)"
} catch {
    # Not in admin group - that's fine
    Write-Host "[INFO] devuser not in Administrators group (good)"
}

# Add to Users group (default local group)
$usersGroup = [ADSI]"WinNT://./Users,group"
try {
    $usersGroup.Add($userAdsPath)
    Write-Host "[INFO] devuser added to Users group"
} catch {
    Write-Host "[INFO] devuser already in Users group"
}

# Create and configure working directory
Write-Host "[BUILD] Configuring C:\workspace..."
New-Item -ItemType Directory -Path "C:\workspace" -Force | Out-Null
icacls "C:\workspace" /grant "$userName`:(OI)(CI)M" /T /C | Out-Null
icacls "C:\workspace" /grant "Users:(OI)(CI)M" /T /C | Out-Null
Write-Host "[OK] C:\workspace permissions configured"

# Create user home directories
$userProfile = "C:\Users\$userName"
New-Item -ItemType Directory -Path "$userProfile\.ssh" -Force | Out-Null
New-Item -ItemType Directory -Path "$userProfile\.jupyter" -Force | Out-Null
New-Item -ItemType Directory -Path "$userProfile\.conda" -Force | Out-Null

# Create PowerShell profile for devuser
$psProfilePath = "$userProfile\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"
New-Item -ItemType Directory -Path (Split-Path $psProfilePath -Parent) -Force | Out-Null

$profileContent = @"
# DevContainer PowerShell Profile
# Auto-generated by devcontainer-win11 build

# Initialize conda
if (Test-Path "C:\conda\Scripts\conda.exe") {
    (& "C:\conda\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
    conda activate main 2>`$null
}

# Free-threading Python env var (should already be set system-wide, ensure visibility)
`$env:Py_GIL_DISABLED = "1"

# Set working directory
if (Test-Path "C:\workspace") {
    Set-Location "C:\workspace"
}

# UTF-8 encoding
chcp 65001 | Out-Null
"@
Set-Content -Path $psProfilePath -Value $profileContent -Encoding UTF8
Write-Host "[OK] PowerShell profile created for devuser"

# Create conda init for system
$condaInitPs1 = "C:\conda\shell\condabin\conda-hook.ps1"
if (Test-Path $condaInitPs1) {
    Write-Host "[OK] conda hook script exists at $condaInitPs1"
}

# Configure Jupyter directories
$jupyterDataDir = "C:\ProgramData\jupyter"
New-Item -ItemType Directory -Path $jupyterDataDir -Force | Out-Null

# Set permissions for devuser directories
icacls $userProfile /grant "$userName`:(OI)(CI)F" /T /C | Out-Null
icacls "C:\ProgramData\ssh" /grant "$userName`:(OI)(CI)RX" /T /C | Out-Null
icacls $jupyterDataDir /grant "$userName`:(OI)(CI)RX" /T /C | Out-Null

# Configure SSH directory permissions
$sshDir = "C:\ProgramData\ssh"
icacls $sshDir /grant "Administrators:(OI)(CI)F" /T /C | Out-Null
icacls $sshDir /grant "SYSTEM:(OI)(CI)F" /T /C | Out-Null

# Set entrypoint and healthcheck to be executable
icacls "C:\ProgramData\devcontainer" /grant "Everyone:(OI)(CI)RX" /T /C | Out-Null

# Copy PowerShell profile to System32 (for all users)
$systemProfile = "C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1"
$systemProfileContent = @"
# System PowerShell profile for DevContainer Win11
chcp 65001 | Out-Null
if (Test-Path "C:\conda\Scripts\conda.exe") {
    (& "C:\conda\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
}
`$env:Py_GIL_DISABLED = "1"
"@
Set-Content -Path $systemProfile -Value $systemProfileContent -Encoding UTF8 -ErrorAction SilentlyContinue

Write-Host "[INFO] devuser user info:"
$userInfo = Get-LocalUser -Name $userName
Write-Host "  - Name: $($userInfo.Name)"
Write-Host "  - Enabled: $($userInfo.Enabled)"
Write-Host "  - Description: $($userInfo.Description)"
$isAdmin = (Get-LocalGroupMember -Name Administrators -Member $userName -ErrorAction SilentlyContinue) -ne $null
Write-Host "  - Is Administrator: $isAdmin"

Write-Host "[OK] Stage 6: devuser created, directories configured, entrypoint ready"
